import type { Metadata } from "next"
import "./globals.css"
import { auth } from "@/auth"
import { SessionProvider } from "next-auth/react"
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default async function RootLayout({ children }:
	Readonly<{ children: React.ReactNode }>) {
	const session = await auth()
	return (
		<SessionProvider session={session}>
		<html lang="en">
			<Toaster />
			<body>{children}</body>
		</html>
		</SessionProvider>
	)
}
